# ------------------
# Global Settings
# ------------------
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

# ------------------
# Top-level Remappings (for older Foundry versions)
# ------------------
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# ------------------
# RPC Endpoints
# ------------------
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# ------------------
# Etherscan Configuration
# ------------------
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# ------------------
# Profile for Mainnet (High Optimization)
# ------------------
[profile.mainnet]
optimizer = true
optimizer_runs = 200000
via_ir = true
